### ISSUE TITLE
Be sure to replace mysite/apps with your_username/apps

### ISSUE THREAD

**Issue by RichardBH** [tomcam/py4webcasts#5]
Replace the contents of bottle_app.py as follows. Be sure to replace mysite/apps with your_username/apps, where your_username is your PythonAnywhere username.

This line is very confusing, does it mean inside the bottle.py contents that you should copy from below. But that should just be left as is. (i replaced APPS_FOLDER = 'apps' with APPS_FOLDER = '<myusername>/apps' but it didnt work.

This should just be left as is with APPS_FOLDER = 'apps'

In the line above you reference the file from ~ (home) so this line is not needed:
_"Be sure to replace mysite/apps with your_username/apps, where your_username is your PythonAnywhere username."_

**Comment by tomcam** [comment]
Good call! Would you mind checking it now? I think I nailed it but could use a second pair of eyes. 
Thanks a million for your feedback.
