### ISSUE TITLE
Visit your website - click link in web tab.

### ISSUE THREAD

**Issue by RichardBH** [tomcam/py4webcasts#7]
You can also click on the link in the pythonanywhere web tab. whefe it says: Configuration for <your site name>.pythonanywhere.com above the reload button.

https://github.com/tomcam/py4webcasts/blob/master/docs/how-install-source-pythonanywhere.md#visit-your-website

**Comment by tomcam** [comment]
Richard, I just read this. Thank you! Added to the tutorial immediately!
